ktor {
    deployment {
        port = 8038
    }
    application {
        modules = [ com.vt.ApplicationKt.module ]
    }
    database {
        url      = ${DATABASE_URL}
        driver   = "org.postgresql.Driver"
        user     = ${DATABASE_USER}
        password = ${DATABASE_PASSWORD}
    }
}
