#!/bin/bash
set -e

until pg_isready -U "$POSTGRES_USER"; do
    sleep 2
done

psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "CREATE DATABASE \"$APP_DATABASE\";"
psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "CREATE USER \"$ADMIN_USER\" WITH SUPERUSER PASSWORD '$ADMIN_PASSWORD';"


psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "CREATE USER \"$TEMPORAL_USER\" WITH SUPERUSER PASSWORD '$TEMPORAL_PASSWORD';"
psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "CREATE DATABASE \"$TEMPORAL_DB\" OWNER \"$TEMPORAL_USER\";"

echo "Database creation done"