ktor {
    deployment {
        port = 8037
    }
    application {
        modules = [ com.vt.ApplicationKt.module ]
    }
    clickhouse {
        url      = ${CLICKHOUSE_URL}
        user     = ${CLICKHOUSE_USER}
        password = ${CLICKHOUSE_PASSWORD}
    }
}
