CREATE TABLE IF NOT EXISTS accounts (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_name  text NOT NULL,
  balance     numeric(12, 2) NOT NULL CHECK (balance >= 0)
);

CREATE TABLE IF NOT EXISTS transfers (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_account_id  integer NOT NULL REFERENCES accounts(id),
  to_account_id    integer NOT NULL REFERENCES accounts(id),
  amount           numeric(12, 2) NOT NULL CHECK (amount > 0),
  note             text NOT NULL DEFAULT '',
  created_at       timestamptz NOT NULL DEFAULT now()
);
