ktor {
    deployment {
        port = 8036
    }
    application {
        modules = [ com.vt.ApplicationKt.module ]
    }
    database {
        url = ${DATABASE_URL}
        driver = "org.postgresql.Driver"
        user = ${DATABASE_USER}
        password = ${DATABASE_PASSWORD}
    }
    jwt {
        issuer = "mybrokerapp-auth"
        issuer = ${?JWT_ISSUER}
        audience = "mybrokerapp"
        audience = ${?JWT_AUDIENCE}
        privateKeyPath = "classpath:keys/dev-private.pem"
        privateKeyPath = ${?JWT_PRIVATE_KEY_PATH}
        publicKeyPath = "classpath:keys/dev-public.pem"
        publicKeyPath = ${?JWT_PUBLIC_KEY_PATH}
        accessTtlMinutes = 15
        accessTtlMinutes = ${?JWT_ACCESS_TTL_MINUTES}
        refreshTtlDays = 30
        refreshTtlDays = ${?JWT_REFRESH_TTL_DAYS}
    }
}
