ktor {
    deployment {
        port = 8032
    }
    application {
        modules = [ com.vt.ApplicationKt.module ]
    }
    database {
        url = ${DATABASE_URL}
        driver = "org.postgresql.Driver"
        user = ${DATABASE_USER}
        password = ${DATABASE_PASSWORD}
    }
}
notification {
    enabled = false
    enabled = ${?NOTIFICATION_ENABLED}
    attribute_change_exchange = "attribute_change_exchange"
    attribute_change_exchange = ${?ATTRIBUTE_NOTIFICATION_EXCHANGE}
    rabbitmq {
        host = "localhost"
        host = ${?RABBITMQ_HOST}
        port = 5672
        port = ${?RABBITMQ_PORT}
        virtualHost = "/"
        virtualHost = ${?RABBITMQ_VHOST}
        username = "guest"
        username = ${?RABBITMQ_USER}
        password = "guest"
        password = ${?RABBITMQ_PASSWORD}
    }
}
