SELECT DISTINCT ID_STOP, ID_DIRECTION
FROM ROUTE_BY_STOPS
WHERE ROUTE_NUMBER = 11
AND ID_STOP IN (15553, 27167);

SELECT ID_STOP, STOP_NAME, LATITUDE, LONGITUDE
FROM STOPS
WHERE ID_STOP = 15553;

SELECT r2.ID_STOP AS Nearest_Opposite_Stop,
       r2.DISTANCE_BACK,
       s2.LATITUDE,
       s2.LONGITUDE
FROM ROUTE_BY_STOPS r1
JOIN ROUTE_BY_STOPS r2 ON r1.ROUTE_NUMBER = r2.ROUTE_NUMBER
JOIN STOPS s1 ON r1.ID_STOP = s1.ID_STOP
JOIN STOPS s2 ON r2.ID_STOP = s2.ID_STOP
WHERE r1.ROUTE_NUMBER = 11
AND r1.ID_STOP = 15553
AND r2.ID_DIRECTION <> r1.ID_DIRECTION
ORDER BY ABS(s1.LATITUDE - s2.LATITUDE) + ABS(s1.LONGITUDE - s2.LONGITUDE) ASC
LIMIT 1;

SELECT r2.ID_STOP AS Nearest_Opposite_Stop,
       CoordinateDistance(s1.LATITUDE, s1.LONGITUDE, s2.LATITUDE, s2.LONGITUDE) AS Distance_Meters
FROM ROUTE_BY_STOPS r1
JOIN ROUTE_BY_STOPS r2 ON r1.ROUTE_NUMBER = r2.ROUTE_NUMBER
JOIN STOPS s1 ON r1.ID_STOP = s1.ID_STOP
JOIN STOPS s2 ON r2.ID_STOP = s2.ID_STOP
WHERE r1.ROUTE_NUMBER = 11
AND r1.ID_STOP = 15553
AND r2.ID_DIRECTION <> r1.ID_DIRECTION
ORDER BY Distance_Meters ASC
LIMIT 1;

SELECT r2.ID_STOP AS Nearest_Opposite_Stop,
       r2.STOP_NUMBER AS Nearest_Stop_Number,
       CoordinateDistance(s1.LATITUDE, s1.LONGITUDE, s2.LATITUDE, s2.LONGITUDE) AS Distance_Meters
FROM ROUTE_BY_STOPS r1
JOIN ROUTE_BY_STOPS r2 ON r1.ROUTE_NUMBER = r2.ROUTE_NUMBER
JOIN STOPS s1 ON r1.ID_STOP = s1.ID_STOP
JOIN STOPS s2 ON r2.ID_STOP = s2.ID_STOP
WHERE r1.ROUTE_NUMBER = 11
AND r1.ID_STOP = 15553
AND r2.ID_DIRECTION <> r1.ID_DIRECTION
ORDER BY Distance_Meters ASC
LIMIT 1;

SELECT STOP_NUMBER
FROM ROUTE_BY_STOPS
WHERE ROUTE_NUMBER = 11
AND ID_STOP = 27167;
