spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.sql.init.mode=always
app.security.jwt.secret=zmNVBjHVFjhWVFJVFEGveJFV<MFen,nbaewfkchgfFEFWFw
logging.console.enabled=true
app.security.jwt.expiration=3600000
app.security.cors.allowed-origins=*
app.security.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS