services:
  pg-primary:
    image: postgres:16
    container_name: pg-primary
    hostname: pg-primary
    command: ["sleep", "infinity"]
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - pg-lab
    volumes:
      - type: volume
        source: primary-data
        target: /var/lib/postgresql/data/pgdata
      - type: bind
        source: ./artifacts/primary/logs
        target: /var/lib/postgresql/pglogs
      - type: bind
        source: ./artifacts/primary/archive
        target: /var/lib/postgresql/archive

  pg-standby:
    image: postgres:16
    container_name: pg-standby
    hostname: pg-standby
    command: ["sleep", "infinity"]
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - pg-lab
    volumes:
      - type: volume
        source: standby-data
        target: /var/lib/postgresql/data/pgdata
      - type: bind
        source: ./artifacts/standby/logs
        target: /var/lib/postgresql/pglogs
      - type: bind
        source: ./artifacts/standby/archive
        target: /var/lib/postgresql/archive

  client:
    image: postgres:16
    container_name: pg-client
    hostname: client
    command: ["sleep", "infinity"]
    stdin_open: true
    tty: true
    working_dir: /workspace
    networks:
      - pg-lab
    volumes:
      - type: bind
        source: .
        target: /workspace

networks:
  pg-lab:
    name: pg-lab
    driver: bridge

volumes:
  primary-data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=256m,uid=999,gid=999,mode=0700
  standby-data:
