package ru.itmo.blps.app.models.enums;

public enum OrderStatus {
    CHECKED_OUT,
    FULFILLMENT_SELECTED,
    WAITING_PAYMENT,
    PAID,
    PICKUP_SHOP_SELECTED,
    PICKUP_NOTIFIED_TO_SHOP,
    PICKUP_PREPARING,
    READY_FOR_PICKUP,
    READY_NOTIFICATION_SENT,
    DELIVERY_ADDRESS_PROVIDED,
    COURIER_ASSIGNED,
    COURIER_PICKED_UP,
    COURIER_DELIVERED,
    RECEIVED,
    COMPLETED
}
