ktor {
    deployment {
        port = 8033
    }
    application {
        modules = [ com.vt.ApplicationKt.module ]
    }
    database {
        url = ${DATABASE_URL}
        driver = "org.postgresql.Driver"
        user = ${DATABASE_USER}
        password = ${DATABASE_PASSWORD}
    }
}
application {
    api_gateway_url = "http://localhost:8050"
    api_gateway_url = ${?API_GATEWAY_URL}
    attribute_change_ntf_queue = "clients.attribute.ntf.balm"
    attribute_change_ntf_queue = ${?ATTRIBUTE_CHANGE_NTF_QUEUE}
    refs_sync_required = true
    refs_sync_required = ${?REFS_SYNC_REQUIRED}
    report_request_exchange = "balm.reports.daily"
    report_request_exchange = ${?REPORT_REQUEST_EXCHANGE}
    report_scheduling_enabled = true
    report_scheduling_enabled = ${?REPORT_SCHEDULING_ENABLED}
}

rabbitmq {
    host = "localhost"
    host = ${?RABBITMQ_HOST}
    port = 5672
    port = ${?RABBITMQ_PORT}
    virtualHost = "/balm"
    virtualHost = ${?RABBITMQ_VHOST}
    username = "admin"
    username = ${?RABBITMQ_USER}
    password = "admin"
    password = ${?RABBITMQ_PASSWORD}
}
