server {
    listen 8050;

    server_tokens off;

    location /test {
        root /var/www/html/test;
        try_files $uri $uri/ /index.html =404;
    }

    location /api/v1/refs {  
        proxy_pass http://refs;           
        proxy_set_header Host $host; 
    }  

    location /api/v1/clients {  
        proxy_pass http://clients;
        proxy_set_header Host $host;  
    }  

    location /api/v1/auth {
        proxy_pass http://auth;
        proxy_set_header Host $host;
    }

    location /api/v1/balm {  
        proxy_pass http://balm;
        proxy_set_header Host $host;  
    }  

    location /api/v1/depository {  
        proxy_pass http://depository;
        proxy_set_header Host $host;  
    }  

    location /api/v1/orders {  
        proxy_pass http://orders;  
        proxy_set_header Host $host;  
    }  

    location /api/v1/core-gateway {
        proxy_pass http://core_gateway;
        proxy_set_header Host $host;
    }

    location /api/v1/data_collector {  
        proxy_pass http://data_collector;
        proxy_set_header Host $host;  
    }

    location /api/v1/exchange/ {
        proxy_pass http://exchange_adapter/;
        proxy_set_header Host $host;
    }

    location /v1/stocks {
        proxy_pass http://market_data;
        proxy_set_header Host $host;
    }

    location /v1/fx {
        proxy_pass http://market_data;
        proxy_set_header Host $host;
    }

    location /v1/reports {
        proxy_pass http://reporting;
        proxy_set_header Host $host;
    }

    location /v1/templates {
        proxy_pass http://reporting;
        proxy_set_header Host $host;
    }

    location /v1/notifications {
        proxy_pass http://notify;
        proxy_set_header Host $host;
    }
}