upstream refs {
    zone refs_zone 64k;
    server core-refs:8031 resolve;
} 

upstream clients {
    zone clients_zone 64k;
    server core-clients:8032 resolve;
}

upstream auth {
    zone auth_zone 64k;
    server core-auth:8036 resolve;
}

upstream data_collector {
    zone data_collector_zone 64k;
    server core-mocker:8030 resolve;
}

upstream exchange_adapter {
    zone exchange_adapter_zone 64k;
    server exchange-adapter:8040 resolve;
}

upstream balm {
    zone balm_zone 64k;
    server core-balm:8033 resolve;
}

upstream depository {
    zone depository_zone 64k;
    server core-depository:8034 resolve;
} 

upstream orders {
    zone orders_zone 64k;
    server core-orders:8035 resolve;
}

upstream core_gateway {
    zone core_gateway_zone 64k;
    server core-gateway:8062 resolve;
}

upstream market_data {
    zone market_data_zone 64k;
    server core-mds:8037 resolve;
}

upstream reporting {
    zone reporting_zone 64k;
    server core-rep:8038 resolve;
}

upstream notify {
    zone notify_zone 64k;
    server core-notify:8039 resolve;
}